export const VACCINE_LIST_COUNTRY_SUCCESS = 'VACCINE_LIST_COUNTRY_SUCCESS';
export const VACCINE_LIST_COUNTRY_FAIL = 'VACCINE_LIST_COUNTRY_FAIL';

export const VACCINE_LIST_CONTINENT_SUCCESS = 'VACCINE_LIST_CONTINENT_SUCCESS';
export const VACCINE_LIST_CONTINENT_FAIL = 'VACCINE_LIST_CONTINENT_FAIL';
